const Discord = require("discord.js");
const fs = require("fs");
const inquirer = require("inquirer");
const reload = require("require-reload")(require);
const Sequelize = require("sequelize");

const logger = require("./util/logger");

class Application {
  constructor() {
    logger.info("Application started");

    this._setup();
  }

  embed(options) {
    return Object.assign({
      title: `${this.client.user.username || null}`,
      color: 0x0086FF,
      // TODO: url: `https://`,
    }, options || {});
  }

  async _configSetup() {
    logger.log("\nWelcome! Let's get your bot set up.\n");

    const promptResponse = await inquirer.prompt([
      {
        type: "input",
        name: "token",
        message: "Bot token:",
      },
      {
        type: "input",
        name: "db_host",
        message: "Database host:"
      },
      {
        type: "input",
        name: "db_user",
        message: "Database username:"
      },
      {
        type: "password",
        name: "db_pass",
        message: "Database password:"
      },
      {
        type: "input",
        name: "db_name",
        message: "Database name:"
      },
    ]);

    logger.log("");

    try {
      await fs.writeFile("./config.json", JSON.stringify({
        _comment: "DO NOT EDIT THIS FILE YOURSELF. If you break something in here, it's entirely your fault.",
        token: promptResponse.token,
        database: {
          host: promptResponse.db_host,
          user: promptResponse.db_user,
          pass: promptResponse.db_pass,
          name: promptResponse.db_name,
        },
      }, null, 2), "utf8");
      logger.info("autoconfig", "Config saved.");
    } catch(err) {
      logger.error("autoconfig", `Error saving configuration: ${err.message}`);
      process.exit(0);
    }
  }

  _setup() {
    try {
      this.config = require("./config.json");
    } catch(err) {
      this._configSetup();
      this.config = require("./config.json");
    }

    console.log(this.config);

    // == TODO ==
    // this.client = new Discord.Client({
    //   disabledEvents: [
    //     "TYPING_START", "PRESENCE_UPDATE"
    //   ]
    // });

    // this.config = require("./config.json");

    // this.database = new Sequelize({
    //   dialect: "mysql",
    //   host: this.config.db.host,
    //   username: this.config.db.user,
    //   password: this.config.db.pass,
    //   database: this.config.db.database,
    //   // TODO: logging: [function Function],
    // });
  }
}

module.exports = Application;

new Application();

process.on("unhandledRejection", async (reason, promise) => {
  promise = require("util").inspect(promise, false, 2);
  logger.error("promise", `${promise}`);
});

